version: "4"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    volumes:
      - ./data:/var/lib/postgresql/data
  keydb:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    ports:
      - "6379:6379"
